name = "MultiDimEquations"
uuid = "a3219271-55cc-59b6-9a1f-6f3111928ce1"
authors = ["Antonello Lobianco <antonello@lobianco.org>"]
version = "2.1.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
IndexedTables = "6deec6e2-d858-57c5-ab9b-e6ca5bd20e43"

[compat]
DataFrames = "0.21, 0.22"
IndexedTables = "0.13"
julia = "1.0"
